### ISSUE TITLE
Opening Component drawer shows many errors

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/ontology-ui#14]
If you open the console, then open the Component drawer, there are many errors generated.  A partial list:

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Blueprint3.Portal

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at Portal (http://localhost:3000/static/js/vendors~main.chunk.js:14410:43)
    at Overlay (http://localhost:3000/static/js/vendors~main.chunk.js:12328:43)
    at Drawer (http://localhost:3000/static/js/vendors~main.chunk.js:6647:38)
    at div
    at OntologyExplorer (http://localhost:3000/static/js/main.chunk.js:539:5)
    at div
    at OntologyExplorer (http://localhost:3000/static/js/main.chunk.js:2177:5)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:124802:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:125004:29)
    at div
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:124433:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:124054:35)
    at App (http://localhost:3000/static/js/main.chunk.js:39:5)
    at HotkeysProvider (http://localhost:3000/static/js/vendors~main.chunk.js:18272:21)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
(anonymous) @ react-dom.development.js:11587
push../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushLegacyContextWarning @ react-dom.development.js:11571
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23819
commitRootImpl @ react-dom.development.js:23005
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Transition, TransitionGroup

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at TransitionGroup (http://localhost:3000/static/js/vendors~main.chunk.js:127118:30)
    at Portal (http://localhost:3000/static/js/vendors~main.chunk.js:14410:43)
    at Overlay (http://localhost:3000/static/js/vendors~main.chunk.js:12328:43)
    at Drawer (http://localhost:3000/static/js/vendors~main.chunk.js:6647:38)
    at div
    at OntologyExplorer (http://localhost:3000/static/js/main.chunk.js:539:5)
    at div
    at OntologyExplorer (http://localhost:3000/static/js/main.chunk.js:2177:5)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:124802:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:125004:29)
    at div
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:124433:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:124054:35)
    at App (http://localhost:3000/static/js/main.chunk.js:39:5)
    at HotkeysProvider (http://localhost:3000/static/js/vendors~main.chunk.js:18272:21)
```

**Comment by bkmartinjr** [comment]
Duplicate of #49
